using System.Runtime.Versioning;

namespace PicView.Core.Linux;

public static class LinuxKeybindings
{
    public const string DefaultKeybindings = """
                                              {
                                                "D": "Next",
                                                "Right": "Next",
                                                "Ctrl+Right": "Last",
                                                "Ctrl+D": "Last",
                                                "Ctrl+Left": "First",
                                                "Ctrl+A": "First",
                                                "Shift+D": "NextFolder",
                                                "Shift+Right": "NextFolder",
                                                "Shift+A": "PrevFolder",
                                                "Shift+Left": "PrevFolder",
                                                "A": "Prev",
                                                "Left": "Prev",
                                                "W": "Up",
                                                "Up": "Up",
                                                "S": "Down",
                                                "Down": "Down",
                                                "PageUp": "ScrollUp",
                                                "PageDown": "ScrollDown",
                                                "Add": "ZoomIn",
                                                "OemPlus": "ZoomIn",
                                                "OemMinus": "ZoomOut",
                                                "Subtract": "ZoomOut",
                                                "Alt+X": "ToggleScroll",
                                                "Home": "ScrollToTop",
                                                "End": "ScrollToBottom",
                                                "G": "ToggleGallery",
                                                "F": "Flip",
                                                "L": "ToggleLooping",
                                                "C": "Crop",
                                                "E": "GalleryClick",
                                                "Return": "GalleryClick",
                                                "I": "ImageInfoWindow",
                                                "F6": "EffectsWindow",
                                                "F1": "AboutWindow",
                                                "F3": "OpenInExplorer",
                                                "Alt+S": "SettingsWindow",
                                                "F5": "Slideshow",
                                                "Ctrl+F": "Fullscreen",
                                                "F11": "Fullscreen",
                                                "B": "ChangeBackground",
                                                "Space": "Center",
                                                "K": "KeybindingsWindow",
                                                "Ctrl+O": "Open",
                                                "Ctrl+E": "OpenWith",
                                                "Ctrl+R": "Reload",
                                                "Ctrl+S": "Save",
                                                "Shift+Ctrl+S": "SaveAs",
                                                "F2": "Rename",
                                                "Ctrl+C": "CopyFile",
                                                "Alt+Ctrl+V": "CopyFilePath",
                                                "Shift+Ctrl+C": "CopyImage",
                                                "Ctrl+X": "CutFile",
                                                "Ctrl+V": "Paste",
                                                "Ctrl+P": "Print",
                                                "Alt+Z": "ToggleInterface",
                                                "Delete": "DeleteFile",
                                                "Shift+Delete": "DeleteFilePermanently",
                                                "Back": "DeleteFile",
                                                "Shift+Back": "DeleteFilePermanently",
                                                "Ctrl+N": "NewWindow",
                                                "J": "ResizeWindow",
                                                "Alt+Ctrl+I": "ResizeWindow",
                                                "Ctrl+F": "Search",
                                                "Ctrl+PageUp": "NextArchive",
                                                "Ctrl+PageDown": "PrevArchive"
                                              }
                                              """;
}
